config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  get 'user/:id', to: 'user#profile', as: 'user'
  get 'about', to: 'pages#about'

  get 'admin', to: 'admin#index'
  get 'admin/posts', to: 'admin#posts'
  get 'admin/comments', to: 'admin#comments'
  get 'admin/users', to: 'admin#users'
  
  resources :posts do
    resources :comments
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  scope :latests, -> { order('created_at DESC')}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  has_rich_text :body

  has_noticed_notifications model_name: 'Notification' 
  after_create_commit :notify_recipient
  before_destroy :cleanup_notifications

  private

  def notify_recipient
    CommentNotification.with(comment: self, post: post).deliver_later(post.user)
  end

  def cleanup_notifications
    notifications_as_comment.destroy_all
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  include Noticed::Model
  belongs_to :recipient, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId

  validates :title, presence: true, length: { in: 3..144 }
  validates :body, presence: true, length: { minimum: 5 }

  belongs_to :user

  has_many :comments, dependent: :destroy

  has_noticed_notifications model_name: 'Notification'
  has_many :notifications, through: :user

  scope :from_user, -> (user_id) { where("user_id = ?", user_id) }

  friendly_id :title, use: %i[ slugged history ]

  private

  def should_generate_new_friendly_id?
    title_changed? || slug.blank?
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  extend FriendlyId
  validates :name, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :notifications, as: :recipient, dependent: :destroy

  before_create :add_author_role

  friendly_id :name, use: %i[ slugged history ]

  private

  def should_generate_new_friendly_id?
    name_changed? || slug.blank?
  end

  def add_author_role
    self.add_role(:author)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_action

  def index
  end

  def posts
    @posts = Post.all.includes(:user)
  end

  def comments
    @comments = Comment.all.includes(:user, :post, :rich_text_body)
  end

  def users
    @users = User.all
  end

  private

  def authorize_action
    authorize nil, policy_class: AdminPolicy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pundit::Authorization
    include Pagy::Backend

    before_action :set_notifications, if: :current_user
    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

    private

    def user_not_authorized
      flash[:alert] = "You are not authorized to perform this action."
      redirect_to(request.referrer || root_path)
    end

    def set_notifications
      notifications = Notification.includes(:recipient).where(recipient: current_user).newest_first
      @unread = notifications.unread
      @read = notifications.read
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_post
    before_action :set_comment, except: %i[ create ]
    before_action :authorize_action, except: %i[ create ]

    def create
      @comment = @post.comments.create(comment_params)
      @comment.user = current_user

      if @comment.save
        redirect_to post_path(@post), notice: "Comment has been created"
      else
        redirect_to post_path(@post), alert: "Comment has not been created"
      end
    end

    def destroy
      @comment.destroy
      redirect_to post_url(@post), notice: "comment has been deleted"
    end

    def update
      if @comment.update(comment_params) then
        redirect_to post_url(@post), notice: "comment has been updated"
      else
        redirect_to post_url(@post), alert: "Comment has not been updated"
      end
    end

    private

    def authorize_action
      authorize @comment
    end

    def set_comment
      @comment = @post.comments.find(params[:id])
    end

    def set_post
      @post = Post.friendly.find(params[:post_id])
    end

    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[ index show ]
  before_action :authorize_action, only: %i[ edit update destroy ]

  def index
    @query = Post.ransack(params[:q])
    @pagy, @posts = pagy(@query.result.includes(:user).latests, items: 9)
  end

  def show
    @post.update(views: @post.views + 1)
    @comments = @post.comments.includes(:user, :rich_text_body).latests

    mark_notification_as_read
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
      redirect_to post_url(@post), notice: "Post was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @post.update(post_params)
      redirect_to post_url(@post), notice: "Post was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy

    redirect_to posts_url, notice: "Post was successfully destroyed."
  end

  private
    def authorize_action
      authorize @post
    end

    def set_post
      @post = Post.friendly.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :body)
    end

    def mark_notification_as_read
      if current_user
        notifications_to_mark_as_read = @post.notifications_as_post.where(recipient: current_user)
        notifications_to_mark_as_read.update_all(read_at: Time.zone.now)
      end
    end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
    class Responder < ActionController::Responder
        def to_turbo_stream
            controller.render(options.merge(formats: :html))
        rescue ActionView::MissingTemplate => e
            if get?
                raise e
            elsif has_errors? && default_action
                render rendering_options.merge(formats: :html, status: :unprocessable_entity)
            else
                redirect_to navigation_location
            end
        end
    end

    self.responder = Responder
    respond_to :html, :turbo_stream
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :set_user

  def profile
    @user.update(views: @user.views + 1)
    @posts = Post.all.includes(:user).from_user(@user.id)
  end

  private

  def set_user
    @user = User.friendly.find(params[:id])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/_link.html.erb
<%= link_to resource.name.capitalize, url_for([:admin, resource]), class: 'btn btn-primary' %>

app/views/admin/_nav_links.html.erb
<div class="text-center">
  <p><%= link_to 'Admin', admin_path %> <%= " > #{params[:action].capitalize}" unless params[:action].eql?("index") %></p>
  <div class="btn-group">
    <%= render 'admin/link', resource: Post %>
    <%= render 'admin/link', resource: Comment %>
    <%= render 'admin/link', resource: User %>
  </div>
</div>

app/views/admin/comments.html.erb
<%= render 'admin/nav_links' %>

<table class="table">
  <thead>
    <th scope="col">Id</th>
    <th scope="col">Comment</th>
    <th scope="col">Post</th>
    <th scope="col">Author</th>
  </thead>
  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <th scope="row"><%= comment.id %></th>
        <th><%= comment.body %></th>
        <td><%= link_to comment.post.title.truncate(75), post_path(comment.post) %></td>
        <td><%= link_to comment.user.name, user_path(comment.user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/index.html.erb
<%= render 'admin/nav_links' %>

app/views/admin/posts.html.erb
<%= render 'admin/nav_links' %>

<table class="table">
  <thead>
    <th scope="col">Id</th>
    <th scope="col">Post</th>
    <th scope="col">Author</th>
    <th scope="col">Comments</th>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <th scope="row"><%= post.id %></th>
        <th><%= link_to post.title.truncate(40), post_path(post) %></th>
        <td><%= link_to post.user.name, user_path(post.user) %></td>
        <td><%= pluralize(post.comments.count, "Comment") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/users.html.erb
<%= render 'admin/nav_links' %>

<table class="table">
  <thead>
    <th scope="col">Id</th>
    <th scope="col">name</th>
    <th scope="col">Posts</th>
    <th scope="col">Comments</th>
    <th scope="col">Is Admin? </th>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <th scope="row"><%= user.id %></th>
        <th><%= link_to user.name, user_path(user) %></th>
        <td><%= pluralize(user.posts.count, "Post") %></td>
        <td><%= pluralize(user.comments.count, "Comment") %></td>
        <td><%= user.has_role?(:admin) ? 'Yes' : 'No' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/_alerts.html.erb
<% if notice %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= notice %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<% elsif alert %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <%= alert%>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
  <div class="container-fluid">
    <%= link_to 'Rails Blog', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse " id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'About', about_path, class: 'nav-link' %>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto mb-s mb-lg-0">
        <%= render 'layouts/notifications' %>
        <%= render 'layouts/session_manager' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_notification.html.erb
<li class="dropdown-item ">
  <%= link_to notification.to_notification.message, notification.to_notification.url , class: "#{notification.read? ? 'text-muted' : ''}" %>
</li>

app/views/layouts/_notifications.html.erb
<% if current_user %>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <span class="badge rounded-pill bg-dark outline-light">
              <%= @unread.count >= 9 ? '9+' : @unread.count %>
              <i class="bi bi-bell"></i>
            </span>
        </a>
        <ul class="dropdown-menu dropdown-menu-lg-end" aria-labelledby="navbarDropdown">
          <% @unread.each do |notification| %>
            <%= render 'layouts/notification', notification: notification %>
          <% end %>

          <% if @read.count > 0 && @unread.count > 0 %>
            <li>
              <hr class="dropdown-divider">
            </li>
          <% elsif @read.count + @unread.count == 0 %>
            <li class="dropdown-item-text">
              Any notifications
            </li>
          <% end %>

          <% @read.each do |notification| %>
            <%= render 'layouts/notification', notification: notification %>
          <% end %>
        </ul>
    </li>
<% end %>

app/views/layouts/_session_manager.html.erb
<% if current_user %>
  <li class="nav-item dropdown">
    <a class="dropdown-toggle btn btn-outline-light" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-person-circle"></i>
      <%= current_user.name %>
    </a>
    <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
      <% if current_user.has_role?(:admin) %>
        <li><%= link_to 'Admin Dashboard', admin_path, class: 'dropdown-item' %></li>
      <% end %>
      <li><%= link_to 'My Profile', user_path(current_user), class: 'dropdown-item' %></li>
      <li><%= link_to 'New Post', new_post_path, class: 'dropdown-item' %></li>
      <li><%= link_to 'Edit Account', edit_user_registration_path, class: 'dropdown-item' %></li>
      <li><hr class="dropdown-divider"></li>
      <li><%= button_to 'Sign out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %></li>
    </ul>
  </li>
<% else %>
 <li class="nav-item">
    <%= link_to 'Login', new_user_session_path, class: 'btn btn-outline-light me-2'%>
  </li>
  <li class="nav-item">
    <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-warning'%>
  </li>
<% end %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </head>

  <body>
    <header class="p-1 mb-3 bg-dark text-white">
      <div class="container">
        <%= render 'layouts/navbar' %>
      </div>
    </header>

    <main class="container">
      <%= render 'layouts/alerts' %>
      <%= yield %>
    </main>

  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>