config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  get 'user/:id', to: 'user#profile', as: 'user'
  get 'about', to: 'pages#about'

  get 'admin', to: 'admin#index'
  get 'admin/posts', to: 'admin#posts'
  get 'admin/comments', to: 'admin#comments'
  get 'admin/users', to: 'admin#users'
  
  resources :posts do
    resources :comments
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId

  validates :title, presence: true, length: { in: 3..144 }
  validates :body, presence: true, length: { minimum: 5 }

  belongs_to :user

  has_many :comments, dependent: :destroy

  has_noticed_notifications model_name: 'Notification'
  has_many :notifications, through: :user

  scope :from_user, -> (user_id) { where("user_id = ?", user_id) }

  friendly_id :title, use: %i[ slugged history ]

  private

  def should_generate_new_friendly_id?
    title_changed? || slug.blank?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[ index show ]
  before_action :authorize_action, only: %i[ edit update destroy ]

  def index
    @query = Post.ransack(params[:q])
    @pagy, @posts = pagy(@query.result.includes(:user).latests, items: 9)
  end

  def show
    @post.update(views: @post.views + 1)
    @comments = @post.comments.includes(:user, :rich_text_body).latests

    mark_notification_as_read
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
      redirect_to post_url(@post), notice: "Post was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @post.update(post_params)
      redirect_to post_url(@post), notice: "Post was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy

    redirect_to posts_url, notice: "Post was successfully destroyed."
  end

  private
    def authorize_action
      authorize @post
    end

    def set_post
      @post = Post.friendly.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :body)
    end

    def mark_notification_as_read
      if current_user
        notifications_to_mark_as_read = @post.notifications_as_post.where(recipient: current_user)
        notifications_to_mark_as_read.update_all(read_at: Time.zone.now)
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <%= render 'posts/post_errors', post: post %>

  <div class="mb-3">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :body, class: "form-label" %>
    <%= form.text_area :body, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.submit "#{action_name} post".capitalize, class: "btn btn-primary" %>
    <%= link_to "Cancel #{action_name}", posts_path, class: "btn btn-danger" %>
  </div>
<% end %>

app/views/posts/_pagination_actions.html.erb
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        <% if @pagy.prev %>
        <li class="page-item">
            <%= link_to "Previous Page", posts_path(page: @pagy.prev), class: "page-link" %>
        </li>
        <% end %>

        <% if @pagy.next %>
        <li class="page-item">
            <%= link_to "Next Page", posts_path(page: @pagy.next), class: "page-link" %>
        </li>
        <% end %>
    </ul>
</nav>

app/views/posts/_post.html.erb
<div id="<%= dom_id(post) %>" class="card my-2">
  <h5 class="card-header text-center">
    <%= post.title %>
  </h5>
  <div class="card-body">
    <h6 class="card-title">
      <small>created by: <%= link_to post.user.name, user_path(post.user) %></small><br />
      <small><%= pluralize(post.views, 'view')%></small>
    </h6>
    <hr />
    <p class="card-text">
      <%= post.body %>
    </p>
    <%= render 'posts/post_actions', post: post %>
  </div>
</div>

app/views/posts/_post_actions.html.erb
<div class="d-flex flex-row justify-content-end">
  <% if current_page?(root_path) or current_page?(user_path) %>
    <%= link_to "Read more", post, class: 'btn btn-sm btn-secondary mx-1' %>
  <% else %>
    <% if current_user == post.user %>
      <%= link_to edit_post_path(post), class: 'btn btn-sm btn-primary mx-1' do %>
        <i class="bi bi-pencil-square"></i>
        Edit this post
      <% end %>
      <%= button_to post, method: :delete, class: 'btn btn-sm btn-danger mx-1' do %>
        <i class="bi bi-trash3"></i>
        Destroy this post
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/posts/_post_errors.html.erb
<% if post.errors.any? %>
  <div>
    <h4><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h4>
    <ul class="list-group">
      <% post.errors.each do |error| %>
        <li class="list-group-item list-group-item-danger"><%= error.full_message %></li>
      <% end %>
    </ul>
    <hr />
  </div>
<% end %>

app/views/posts/_posts.html.erb
<div class="row row-cols-3">
  <% posts.each_with_index do |post, index| %>
    <div class="col">
      <%= render post %>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<div class="h-100 p-5 bg-light border rounded-3">
  <h1>Editing post</h1>
  <hr />
  <%= render "form", post: @post, action_name: "update" %>
</div>

app/views/posts/index.html.erb
<h1>Posts</h1>

<div class="container">
  <%= search_form_for @query, class: 'mb-3' do |f| %>
    <%= f.search_field :title_cont, class: 'form-control', placeholder: 'Search posts by title' %>
  <% end %>

  <%= render 'posts/posts', posts: @posts %>
  <%= render 'posts/pagination_actions' %>
</div>

app/views/posts/new.html.erb
<div class="h-100 p-5 bg-light border rounded-3">
  <h1>New post</h1>
  <hr />
  <%= render "form", post: @post, action_name: "create" %>
</div>

app/views/posts/show.html.erb
<%= render @post %>

<div class="mt-5">
  <h4>Comments</h4>
  <hr />
</div>

<div class="container">
  <%= render 'comments/make_comment', post: @post %>

  <% @comments.each do |comment| %>
    <%= render 'comments/comment', post: @post, comment: comment %>
  <% end %>
</div>